### ISSUE TITLE
Bad project name, should be 'ext-soundtouch'

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/ext-soundtouch#1]
We should rename this to 'citra-emu/ext-soundtouch'.
We already have [this naming scheme in place for the other libs](https://github.com/citra-emu?utf8=%E2%9C%93&query=ext-)

(I've already mentioned this a couple of times on IRC before but felt it would be forgotten if I don't post a reminder issue. It's a minor issue though; probably still a good idea to do it before too many people fork the bad name)

**Comment by MerryMage** [comment]
Renamed & citra-emu/citra#1788
